server:
  port: 8080
spring:
  application:
    name: "manageConstructionRequests"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin:Utpctt21@dbconstructionrequest.nsgyn.mongodb.net/requestConstruction?retryWrites=true&w=majority"
